"""Adds necessary repostories/archives."""

########################################################################
# DO NOT EDIT THIS FILE unless you are inside the
# https://github.com/3rdparty/bazel-rules-picojson repository. If you
# encounter it anywhere else it is because it has been copied there in
# order to simplify adding transitive dependencies. If you want a
# different version of stout follow the Bazel build instructions at
# https://github.com/3rdparty/bazel-rules-picojson.
########################################################################

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

def repos():
    if "com_github_3rdparty_bazel_rules_picojson" not in native.existing_rules():
        git_repository(
            name = "com_github_3rdparty_bazel_rules_picojson",
            commit = "",
            remote = "https://github.com/3rdparty/bazel-rules-picojson",
            shallow_since = " -0700",
        )
